steps:
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'gcr.io/firm-star-336501/nodeapp:$TAG_NAME', '.' ]
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/firm-star-336501/nodeapp:'$TAG_NAME']

- name: 'gcr.io/cloud-builders/kubectl'
  args: ["apply","-f","k8s/deploy.yaml"]
  # args: ["set","image","deployment/nodeapp1","nodeapp=gcr.io/firm-star-336501/nodeapp:$TAG_NAME"]
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=asia-east1-b'
  - 'CLOUDSDK_CONTAINER_CLUSTER=cluster-1'
#  waitFor:
#  - 'push-gcr'
