apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: my-ingress3
  annotations:
    kubernetes.io/ingress.class: "gce"
spec:
  rules:
  - http:
      paths:
      - path: /*
        pathType: ImplementationSpecific
        backend:
          service:
            name: my-deployment-service
            port:
              number: 3000
      - path: /v2/*
        pathType: ImplementationSpecific
        backend:
          service:
            name: nodeapp2
            port:
              number: 3000  
  # - host: v1.example.com
  #   http:
  #     paths:
  #     - path: /
  #       pathType: ImplementationSpecific
  #       backend:
  #         service:
  #           name: my-deployment-service
  #           port:
  #             number: 3000
  # - host: v2.example.com
  #   http:
  #     paths:
  #     - path: /
  #       pathType: ImplementationSpecific
  #       backend:
  #         service:
  #           name: nodeapp2
  #           port:
  #             number: 3000
